FROM redmine:5.0.5

RUN apt-get update \
&& apt-get -y upgrade \
&& apt-get install -y iproute2 iputils-ping curl cron vim

COPY ./mail_renkei.sh /usr/src/redmine/mail_renkei.sh
RUN chmod 777 /usr/src/redmine/mail_renkei.sh

EXPOSE 3000
